//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShoe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietGioHang
    {
        public int MaCTGH { get; set; }
        public int GioHang_ID { get; set; }
        public int SanPham_ID { get; set; }
        public string TenSP { get; set; }
        public int SoLuongMua { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public double TongCong { get; set; }
        public byte[] ImagePath { get; set; }
    
        public virtual GioHang GioHang { get; set; }
    }
}
