//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShoe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGiaoDich
    {
        public int MaLSGD { get; set; }
        public int MaKH { get; set; }
        public int MaDH { get; set; }
        public System.DateTime ThoiGianGD { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
